### ISSUE TITLE
how to get password while start running manager.py

### ISSUE THREAD

**Issue by danielimmanj** [sgrkmr/votm#1]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop:**
 - OS: [e.g. Windows 64-bit]
 - Version [e.g. 1.0.6]

**Additional context**

**Comment by nozwock** [comment]
The password is simply stored as a `SHA256` hash in the config file, you can look it up there.
If no password was already set before i.e. it's the first time the `manage` app is being ran then there is no password set, you can just hit `Ok` to continue.

I'll add in the path for where the config file is stored in the README.
